export const SET_IS_STATE_SIDEBAR = 'SET_IS_STATE_SIDEBAR';
export const SET_USER = 'SET_USER';
export const REHYDRATE_AUTH_STATE = 'REHYDRATE_AUTH_STATE';
export const LOG_OUT = 'LOG_OUT';
export const TOGGLE_FOLLOWING_USER = 'TOGGLE_FOLLOWING_USER';
export const SET_AVATAR = 'SET_AVATAR';
